### ISSUE TITLE
Change lookAhead from returning list to just dataframe

### ISSUE THREAD

**Issue by erossiter** [erossiter/catSurv#7]
Currently, the lookAhead function returns a list where the only element is a data frame.  This is inconvenient for a user, so it would be easier to return just a data frame.  I'm sure there's a way, but right now I only know how to return a list to R within the Rcpp environment.

**Comment by alexjweil** [comment]
I think this may be easier than you think; I may be missing something, but based on a quick look, all you need to do is change the return type of the relevant functions to Rcpp::DataFrame, and then remove the line that wraps the data frame you're already producing in an Rcpp::List.

**Comment by erossiter** [comment]
Fixed on cpu branch.
